title: Aishwarya Pothula
email: aishwarya.pothula@gmail.com
description: Computer Science Doctoral Student, University of Texas at Arlington
baseurl: ""
url: "https://aishwarya.github.io"
github_username:  aishwaryapothula
name: Aishwarya Pothula
theme: jekyll-theme-minimal
